Ignore helm repo (#7)
* Ignore helm-repo

* Add helm package size check

diff --git a/.github/workflows/test-and-publish.yml b/.github/workflows/test-and-publish.yml
--- a/.github/workflows/test-and-publish.yml
+++ b/.github/workflows/test-and-publish.yml
@@ -27,12 +27,21 @@ jobs:
           ssh-key: '${{ secrets.HELM_REPO_SSH_KEY }}'
       - name: Package Chart
         shell: bash
+        env:
+          HELM_MAX_PACKAGE_SIZE: "${{ secrets.HELM_MAX_PACKAGE_SIZE }}"
         run: |
           sed -i -e "s/sha_to_be_replaced/${GITHUB_SHA:0:7}/g" Chart.yaml
           cd helm-repo
           helm package ..
           helm repo index .
           new_archive=$(git ls-files --other --exclude-standard | head -n 1)
+
+          archive_size=$(stat --printf="%s" "$new_archive")
+          max_size=${HELM_MAX_PACKAGE_SIZE:-100000}
+          if [ "$archive_size" -gt "$max_size" ]; then
+            echo "::error::Helm package $new_archive is bigger than limit. ($archive_size > $max_size)"
+            exit 90
+          fi
 
           git config --local user.email "github-actions[bot]@${GITHUB_REPOSITORY/\//.}"
           git config --local user.name "github-actions[bot]"
